openapi: 3.0.3
info:
  title: Mediqe
  version: 1.0.0
  description: Mediqe is a modular, scalable backend system designed for healthcare
    applications, featuring robust user management, appointment scheduling, medical
    records, doctor-patient consultations, and admin/role-based dashboards. Built
    with modern Python/Django best practices and ready for production deployment
paths:
  /api/v1/accounts/profiles/:
    get:
      operationId: api_v1_accounts_profiles_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserProfile'
          description: ''
    post:
      operationId: api_v1_accounts_profiles_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserProfile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserProfile'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
  /api/v1/accounts/profiles/{id}/:
    get:
      operationId: api_v1_accounts_profiles_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user profile.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    put:
      operationId: api_v1_accounts_profiles_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user profile.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserProfile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserProfile'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    patch:
      operationId: api_v1_accounts_profiles_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user profile.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserProfile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserProfile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserProfile'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
          description: ''
    delete:
      operationId: api_v1_accounts_profiles_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user profile.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/accounts/users/:
    get:
      operationId: api_v1_accounts_users_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
    post:
      operationId: api_v1_accounts_users_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/v1/accounts/users/{id}/:
    get:
      operationId: api_v1_accounts_users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this user.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: api_v1_accounts_users_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this user.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: api_v1_accounts_users_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this user.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    delete:
      operationId: api_v1_accounts_users_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this user.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    BloodTypesEnum:
      enum:
      - A+
      - A-
      - B+
      - B-
      - AB+
      - AB-
      - O+
      - O-
      type: string
      description: |-
        * `A+` - A+
        * `A-` - A-
        * `B+` - B+
        * `B-` - B-
        * `AB+` - AB+
        * `AB-` - AB-
        * `O+` - O+
        * `O-` - O-
    GenderEnum:
      enum:
      - Male
      - Female
      - Other
      type: string
      description: |-
        * `Male` - Male
        * `Female` - Female
        * `Other` - Other
    PatchedUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        last_login:
          type: string
          format: date-time
          nullable: true
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly
            assigning them.
        username:
          type: string
          nullable: true
          title: User name
          maxLength: 120
        email:
          type: string
          format: email
          maxLength: 300
        password:
          type: string
          writeOnly: true
          maxLength: 600
        first_name:
          type: string
          nullable: true
          maxLength: 150
        last_name:
          type: string
          nullable: true
          maxLength: 150
        role:
          allOf:
          - $ref: '#/components/schemas/RoleEnum'
          title: User role
        gender:
          allOf:
          - $ref: '#/components/schemas/GenderEnum'
          title: User gender
        date_of_birth:
          type: string
          format: date
          nullable: true
        phone:
          type: string
          nullable: true
          title: Phone number
          maxLength: 15
        address:
          type: string
          nullable: true
          title: User address
          maxLength: 150
        avatar:
          type: string
          format: uri
          nullable: true
          title: User image
        is_active:
          type: boolean
          title: Is user active
        is_staff:
          type: boolean
          title: Is user staff
        is_verified:
          type: boolean
          title: Is user verified or not
        created_at:
          type: string
          format: date-time
          readOnly: true
        extra_info:
          nullable: true
          title: Extra fields and data
        groups:
          type: array
          items:
            type: integer
        user_permissions:
          type: array
          items:
            type: integer
    PatchedUserProfile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          $ref: '#/components/schemas/User'
        insurance_number:
          type: string
          nullable: true
          maxLength: 200
        insurance_company:
          type: string
          nullable: true
          maxLength: 50
        blood_types:
          allOf:
          - $ref: '#/components/schemas/BloodTypesEnum'
          title: Blood type
        chronic_conditions:
          type: string
          nullable: true
        license_number:
          type: string
          nullable: true
          maxLength: 80
        speciality:
          type: string
          nullable: true
          maxLength: 100
        bio:
          type: string
          nullable: true
          title: Biogeraphy
        years_of_experiences:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          nullable: true
          title: Yeasr of experiences
        rating:
          type: number
          format: double
          nullable: true
          title: Raing of profile
        verified:
          type: boolean
    RoleEnum:
      enum:
      - Admin
      - Doctor
      - Patient
      - Nurse
      - Receptionist
      type: string
      description: |-
        * `Admin` - Admin
        * `Doctor` - Doctor
        * `Patient` - Patient
        * `Nurse` - Nurse
        * `Receptionist` - Receptionist
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        last_login:
          type: string
          format: date-time
          nullable: true
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly
            assigning them.
        username:
          type: string
          nullable: true
          title: User name
          maxLength: 120
        email:
          type: string
          format: email
          maxLength: 300
        password:
          type: string
          writeOnly: true
          maxLength: 600
        first_name:
          type: string
          nullable: true
          maxLength: 150
        last_name:
          type: string
          nullable: true
          maxLength: 150
        role:
          allOf:
          - $ref: '#/components/schemas/RoleEnum'
          title: User role
        gender:
          allOf:
          - $ref: '#/components/schemas/GenderEnum'
          title: User gender
        date_of_birth:
          type: string
          format: date
          nullable: true
        phone:
          type: string
          nullable: true
          title: Phone number
          maxLength: 15
        address:
          type: string
          nullable: true
          title: User address
          maxLength: 150
        avatar:
          type: string
          format: uri
          nullable: true
          title: User image
        is_active:
          type: boolean
          title: Is user active
        is_staff:
          type: boolean
          title: Is user staff
        is_verified:
          type: boolean
          title: Is user verified or not
        created_at:
          type: string
          format: date-time
          readOnly: true
        extra_info:
          nullable: true
          title: Extra fields and data
        groups:
          type: array
          items:
            type: integer
        user_permissions:
          type: array
          items:
            type: integer
      required:
      - created_at
      - email
      - gender
      - id
      - password
    UserProfile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          $ref: '#/components/schemas/User'
        insurance_number:
          type: string
          nullable: true
          maxLength: 200
        insurance_company:
          type: string
          nullable: true
          maxLength: 50
        blood_types:
          allOf:
          - $ref: '#/components/schemas/BloodTypesEnum'
          title: Blood type
        chronic_conditions:
          type: string
          nullable: true
        license_number:
          type: string
          nullable: true
          maxLength: 80
        speciality:
          type: string
          nullable: true
          maxLength: 100
        bio:
          type: string
          nullable: true
          title: Biogeraphy
        years_of_experiences:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          nullable: true
          title: Yeasr of experiences
        rating:
          type: number
          format: double
          nullable: true
          title: Raing of profile
        verified:
          type: boolean
      required:
      - blood_types
      - id
      - user
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
